[package]
name = "gift-cipher"
version = "0.1.0"
authors = ["RustCrypto Developers"]
rust-version = "1.85"
edition = "2024"
documentation = "https://docs.rs/gift-cipher"
repository = "https://github.com/RustCrypto/block-ciphers"
license = "MIT OR Apache-2.0"
keywords = ["gift", "block-cipher"]
categories = ["cryptography", "no-std"]
description = "Pure Rust implementation of the Gift block cipher"

[dependencies]
cipher = "0.5"

[dev-dependencies]
cipher = { version = "0.5", features = ["dev"] }
hex-literal = "1"

[features]
zeroize = ["cipher/zeroize"]

[package.metadata.docs.rs]
all-features = true
