[package]
name = "sm4"
version = "0.6.0"
authors = ["RustCrypto Developers"]
edition = "2024"
rust-version = "1.85"
documentation = "https://docs.rs/sm4"
repository = "https://github.com/RustCrypto/block-ciphers"
license = "MIT OR Apache-2.0"
keywords = ["sm4", "block-cipher"]
categories = ["cryptography", "no-std"]
description = "SM4 block cipher algorithm"

[dependencies]
cipher = "0.5"

[dev-dependencies]
cipher = { version = "0.5", features = ["dev"] }
hex-literal = "1"

[features]
zeroize = ["cipher/zeroize"]

[package.metadata.docs.rs]
all-features = true
