[package]
name = "aes"
version = "0.9.3"
authors = ["RustCrypto Developers"]
edition = "2024"
rust-version = "1.89"
documentation = "https://docs.rs/aes"
repository = "https://github.com/RustCrypto/block-ciphers"
license = "MIT OR Apache-2.0"
keywords = ["aes", "rijndael", "block-cipher"]
categories = ["cryptography", "no-std"]
description = "Pure Rust implementation of the Advanced Encryption Standard (a.k.a. Rijndael)"

[dependencies]
cipher = "0.5"
cpubits = "0.1"
zeroize = { version = "1.9", optional = true, default-features = false }

[target.'cfg(any(target_arch = "aarch64", target_arch = "x86_64", target_arch = "x86"))'.dependencies]
cpufeatures = "0.3"

[dev-dependencies]
cipher = { version = "0.5", features = ["dev"] }
hex-literal = "1"

[features]
hazmat = [] # Expose cryptographically hazardous APIs

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(aes_backend_soft, values("compact"))',
    'cfg(aes_backend, values("soft"))',
    'cfg(cpubits, values("16", "32", "64"))'
]

[package.metadata.docs.rs]
all-features = true
