[package]
name = "ofb"
version = "0.5.0"
description = "Output Feedback][OFB] (OFB) block cipher mode of operation"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/ofb"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "block-cipher", "ciphers"]

[dependencies]
cipher = { git = "https://github.com/RustCrypto/traits", branch = "experimental_design" }

[dev-dependencies]
aes = { version = "=0.7.0-pre", path = "../../aes", features = ["force-soft"] }
