[package]
name = "threefish"
version = "0.6.0"
authors = ["The Rust-Crypto Project Developers"]
edition = "2024"
rust-version = "1.85"
documentation = "https://docs.rs/threefish"
repository = "https://github.com/RustCrypto/block-ciphers"
license = "MIT OR Apache-2.0"
keywords = ["threefish", "block-cipher"]
categories = ["cryptography", "no-std"]
description = "Threefish block cipher"

[dependencies]
cipher = { version = "0.5", optional = true }
zeroize = { version = "1.6", optional = true, default-features = false }

[dev-dependencies]
cipher = { version = "0.5", features = ["dev"] }
hex-literal = "1"

[features]
default = ["cipher"]

[package.metadata.docs.rs]
all-features = true
