[package]
name = "speck-cipher"
version = "0.1.0"
authors = ["RustCrypto Developers"]
edition = "2024"
rust-version = "1.85"
documentation = "https://docs.rs/speck-cipher"
repository = "https://github.com/RustCrypto/block-ciphers"
license = "Apache-2.0 OR MIT"
keywords = ["speck", "block-cipher"]
categories = ["cryptography", "no-std"]
description = "Speck block cipher algorithm"

[dependencies]
cipher = "0.5"

[dev-dependencies]
cipher = { version = "0.5", features = ["dev"] }
hex-literal = "1"

[features]
zeroize = ["cipher/zeroize"]

[package.metadata.docs.rs]
all-features = true
